language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.4"
  - "3.5"
  - "pypy3"
sudo: false
# no requirements, but simulate what a user would see
install: pip install .
# download test suite and run tests... submodule? meta testing project with
# all of the reference implementations?
script: 
  - git clone https://github.com/json-ld/json-ld.org.git _json-ld.org
  - python tests/runtests.py -d ./_json-ld.org/test-suite
  - git clone https://github.com/json-ld/normalization.git _normalization
  - python tests/runtests.py -d ./_normalization/tests
notifications:
  email:
    on_success: change
    on_failure: change
